#!/usr/bin/env bash
# install nginx server and change landing content
apt-get -y update
apt-get -y install nginx
service nginx start
echo 'Hello World!' | tee /var/www/html/index.html
service nginx restart
